version: '3.4'

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - identityUrl=http://rent-api
    ports:
      - "5245:80"

  front:
    ports:
      - "3000:3000"